name: flutter_application  # Ensure the name follows naming conventions
description: A new Flutter project

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# Versioning details
version: 1.0.0+1

environment:
  sdk: ">=3.5.1 <4.0.0"  # Specifying a valid SDK range

dependencies:
  flutter:
    sdk: flutter

  # Additional dependencies
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  # Ensures that the Material Icons font is included
  uses-material-design: true

  # Asset management
  assets:
    - assets/images/fox_logo.png
    - assets/images/fx_logo.png
    - assets/images/screen_one.png
    - assets/images/on_hoover_over_input_field.png
    - assets/images/on_hoover_over_login_button.png
    
